services:
    escape_wsse_authentication.provider:
        class:  %escape_wsse_authentication.provider.class%
        arguments: [null, null, null, 300]

    escape_wsse_authentication.listener:
        class:  %escape_wsse_authentication.listener.class%
        arguments: [@security.context, @security.authentication.manager]

    escape_wsse_authentication.entry_point:
        class:  %escape_wsse_authentication.entry_point.class%
        arguments: [@logger, null, "UsernameToken"]

    escape_wsse_authentication.encoder:
        class:  %escape_wsse_authentication.encoder.class%
        arguments: ['sha1', true, 1]

    escape_wsse_authentication.nonce_cache:
        class:  %escape_wsse_authentication.nonce_cache.class%
        arguments: [%kernel.cache_dir%/security/nonces]