language: php

php:
  - 5.3
  - 5.4

env:
  - SYMFONY_VERSION=origin/2.1

before_script:
    - curl -s http://getcomposer.org/installer | php
    - php composer.phar install --dev
    - mkdir -p "Tests/nonceDir"

branches:
  except:
    - 2.0.x

notifications:
  email:
    - dev@escapestudios.com
